[package]
name = "quizx"
version = "0.1.0"
authors = ["Aleks Kissinger <aleks0@gmail.com>"]
edition = "2018"
default-run = "simp_and_extract"

[dependencies]
num = "0.3.1"
rustc-hash = "1.1.0"
ndarray = { version = "0.14.0", features = [ "rayon" ] }
approx = "0.4.0"
regex = "1.4.3"
rand = "0.8.3"
