[package]
name = "quizx"
version = "0.1.0"
authors = ["Aleks Kissinger <aleks0@gmail.com>"]
edition = "2018"
default-run = "scratch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
rustc-hash = "1.1.0"
ndarray = { version = "0.14.0", features = [ "rayon" ] }
approx = "0.4.0"
regex = "1.4.3"
